workflows:
  flutter-ci-release:
    name: Flutter CI/CD - ColorSlash
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      vars:
    JAVA_TOOL_OPTIONS: "-Xmx4096m"
        KEYSTORE_PATH: "android/app/keystore.jks"
        KEY_ALIAS: "upload"
      groups:
        - keystore_credentials

    scripts:
      - name: Flutter clean
        script: |
          flutter clean
      - name: Install dependencies
        script: |
          flutter pub get
          
        - name: Flutter pub upgrade --major-versions
        script: |
          flutter pub upgrade 
          
      - name: Generate launcher icons
        script: |
          flutter pub run flutter_launcher_icons:main
      - name: Build Debug APK
        script: |
          flutter build apk --debug
      - name: Build Release APK
        script: |
          flutter build apk --release \
            --build-name=0.1 \
            --build-number=1 \
            --dart-define=FLAVOR=production
      - name: Build iOS release
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/flutter-apk/app-debug.apk
      - build/ios/iphoneos/*.app
      - build/ios/iphoneos/*.ipa
      - build/**/*.aab

    publishing:
      email:
        recipients:
          - luca.bixx93@gmail.com 
        notify:
          success: true
          failure: true



