workflows:
      android-apk-release:
    name: Android APK Release Workflow
    max_build_duration: 60
  flutter-build:
    name: Flutter build
    environment:
      flutter: stable
    scripts:

    environment:
      flutter: stable
      java: 17
      - name: clean
       script: flutter clean
      - name: Get packages
        script: flutter pub get
      - name: Generate launcher icons
        script: flutter pub run flutter_launcher_icons:main
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
 publishing:
      email:
        recipients:
          - luca.bixx@hotmail.it
      

workflows:
  android-apk-debug:
    name: Android APK Debug Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Pulizia e dipendenze
        script: |
          flutter clean
          flutter pub get

      - name: Build APK debug
        script: |
          flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
   


    scripts:
      - name: Aggiorna dipendenze Flutter
        script: |
          flutter pub upgrade --major-versions
      - name: Pulizia progetto
        script: |
      
          flutter clean
          flutter pub get
         
