name: colorslash
description: Un'app di note multimediali - Versione di Test BETA1
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2 
  cloud_firestore: ^5.5.0  
  audioplayers: ^6.0.0  
  path_provider: ^2.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png

