name: colorslash
description: App per note multimediali
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Storage locale
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  uuid: ^4.2.0

  # Firebase (core, auth, firestore, storage)
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2

  # Media
  image_picker: ^1.2.0
  video_player: ^2.10.0
  flutter_sound: ^9.28.0
  file_picker: ^10.3.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"